/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./../components/DarkToggle.vue')['default']
    IMdiArrowRightThick: typeof import('~icons/mdi/arrow-right-thick')['default']
    IMdiBookOutline: typeof import('~icons/mdi/book-outline')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on')['default']
    IMdiLightbulbOutline: typeof import('~icons/mdi/lightbulb-outline')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IMdiWebOff: typeof import('~icons/mdi/web-off')['default']
    LoginForm: typeof import('./../components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
