/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./../components/DarkToggle.vue')['default']
    ExpiryTime: typeof import('./../components/ExpiryTime.vue')['default']
    FooterInfo: typeof import('./../components/FooterInfo.vue')['default']
    IMdiArrowRightThick: typeof import('~icons/mdi/arrow-right-thick')['default']
    IMdiBookOutline: typeof import('~icons/mdi/book-outline')['default']
    IMdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiKeyChain: typeof import('~icons/mdi/key-chain')['default']
    IMdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on')['default']
    IMdiLightbulbOutline: typeof import('~icons/mdi/lightbulb-outline')['default']
    IMdiLoading: typeof import('~icons/mdi/loading')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiWebOff: typeof import('~icons/mdi/web-off')['default']
    InviteAdd: typeof import('./../components/InviteAdd.vue')['default']
    LoginForm: typeof import('./../components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./../components/Toast.vue')['default']
    ToastContainer: typeof import('./../components/ToastContainer.vue')['default']
  }
}
